// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: prime.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThatsJustPrime_ThatsJustPrime_FullMethodName = "/prime.ThatsJustPrime/ThatsJustPrime"
)

// ThatsJustPrimeClient is the client API for ThatsJustPrime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThatsJustPrimeClient interface {
	ThatsJustPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeResponse], error)
}

type thatsJustPrimeClient struct {
	cc grpc.ClientConnInterface
}

func NewThatsJustPrimeClient(cc grpc.ClientConnInterface) ThatsJustPrimeClient {
	return &thatsJustPrimeClient{cc}
}

func (c *thatsJustPrimeClient) ThatsJustPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ThatsJustPrime_ServiceDesc.Streams[0], ThatsJustPrime_ThatsJustPrime_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PrimeRequest, PrimeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThatsJustPrime_ThatsJustPrimeClient = grpc.ServerStreamingClient[PrimeResponse]

// ThatsJustPrimeServer is the server API for ThatsJustPrime service.
// All implementations must embed UnimplementedThatsJustPrimeServer
// for forward compatibility.
type ThatsJustPrimeServer interface {
	ThatsJustPrime(*PrimeRequest, grpc.ServerStreamingServer[PrimeResponse]) error
	mustEmbedUnimplementedThatsJustPrimeServer()
}

// UnimplementedThatsJustPrimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThatsJustPrimeServer struct{}

func (UnimplementedThatsJustPrimeServer) ThatsJustPrime(*PrimeRequest, grpc.ServerStreamingServer[PrimeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ThatsJustPrime not implemented")
}
func (UnimplementedThatsJustPrimeServer) mustEmbedUnimplementedThatsJustPrimeServer() {}
func (UnimplementedThatsJustPrimeServer) testEmbeddedByValue()                        {}

// UnsafeThatsJustPrimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThatsJustPrimeServer will
// result in compilation errors.
type UnsafeThatsJustPrimeServer interface {
	mustEmbedUnimplementedThatsJustPrimeServer()
}

func RegisterThatsJustPrimeServer(s grpc.ServiceRegistrar, srv ThatsJustPrimeServer) {
	// If the following call pancis, it indicates UnimplementedThatsJustPrimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThatsJustPrime_ServiceDesc, srv)
}

func _ThatsJustPrime_ThatsJustPrime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ThatsJustPrimeServer).ThatsJustPrime(m, &grpc.GenericServerStream[PrimeRequest, PrimeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThatsJustPrime_ThatsJustPrimeServer = grpc.ServerStreamingServer[PrimeResponse]

// ThatsJustPrime_ServiceDesc is the grpc.ServiceDesc for ThatsJustPrime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThatsJustPrime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prime.ThatsJustPrime",
	HandlerType: (*ThatsJustPrimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ThatsJustPrime",
			Handler:       _ThatsJustPrime_ThatsJustPrime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime.proto",
}
